stages:
                   
  - stage: STAGE_B
    displayName: STAGE_B
    variables:
    - group: DEV
    jobs:
      - job: job
        displayName: job_b
        steps:
          - bash: |
              # export DECODE_STRING=$(echo "$SSH_KEY" | base64 --decode)
              # mkdir -p ~/.ssh
              # chmod 700 ~/.ssh
              # echo "$DECODE_STRING" > ~/.ssh/id_rsa
              # chmod 600 ~/.ssh/id_rsa

              # eval "$(ssh-agent -s)"
              # ssh-add ~/.ssh/id_rsa
              # ssh -o StrictHostKeyChecking=no -T git@github.com
              
              # Get the latest commit hash
              latest_commit=$(git rev-parse HEAD)
              echo $latest_commit

              # # Get the previous commit hash
              # previous_commit=$(git diff HEAD..origin/master)
              # echo $previous_commit

              # # List the files that have changed between the two commits
              # changed_files=$(git diff --name-only $previous_commit $latest_commit)
              # echo $changed_files
              echo "uno"
              test2=$(git log)
              echo "$test2"

              echo "dos"
              test=$(git branch --list)
              echo "$test"

              echo "tres"
              ls -la