trigger:
  - dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build stage

    variables:
      - group: "node-app-amplify"

    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.0.0"
            displayName: "Install Node.js"

          - script: |
               yarn install
               yarn run build            
            displayName: "yarn install and build"

          - script: |
              echo $(REACT_APP_PRUEBA)
              ls build/

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/build"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true
            displayName: Compress the ./build folder

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: $(Build.BuildId)
            displayName: Publish build artifacts

  - stage: Deploy
    displayName: Deploy amplify

    variables:
      - group: "node-app-amplify-deploy"

    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download Build Artifacts"
            inputs:
              artifactName: $(Build.BuildId)
              downloadPath: $(System.DefaultWorkingDirectory)

          - script: |
               ls -la           
            displayName: "yarn install and build"

          - task: AWSShellScript@1
            inputs:
              awsCredentials: AWS AMOLANO ENV
              regionName: $(AwsRegion)
              scriptType: "inline"
              failOnStandardError: true
              inlineScript: |
                export DEPLOY_RES=$(aws amplify create-deployment --app-id $(AmplifyAppId) --branch-name $(AmplifyBranchName) --no-cli-pager)
                export DEPLOY_JOB_ID=$(echo $DEPLOY_RES | jq -r ".jobId")
                export DEPLOY_URL=$(echo $DEPLOY_RES | jq -r ".zipUploadUrl")

                curl -s --location --request PUT "$DEPLOY_URL" \
                    --header 'Content-Type: application/zip' \
                    --data-binary '@/$(System.DefaultWorkingDirectory)/$(Build.BuildId)/$(Build.BuildId).zip'

                aws amplify start-deployment --app-id $(AmplifyAppId) --branch-name $(AmplifyBranchName) --job-id $DEPLOY_JOB_ID
            displayName: Create Amplify Deployment


              # yarn install
              # ls
              # export REACT_APP_PRUEBA=$(PRUEBA)
              # echo "---------------------------------------------"
              # echo $PRUEBA
              # yarn run build
              # ls build